"""baseline schema 0.2

Revision ID: 4c4d40c18081
Revises: 
Create Date: 2026-07-25 07:17:21.794028

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '4c4d40c18081'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('school_year', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('form_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('page_width_mm', sa.Float(), nullable=False),
    sa.Column('page_height_mm', sa.Float(), nullable=False),
    sa.Column('aspect_ratio', sa.Float(), nullable=False),
    sa.Column('qr_region', sa.JSON(), nullable=False),
    sa.Column('answer_regions', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('hardware_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=96), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('expected_answer', sa.Text(), nullable=False),
    sa.Column('answer_region_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_external_id'), ['external_id'], unique=True)

    op.create_table('camera_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('device_label', sa.String(length=255), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('work_area_polygon', sa.JSON(), nullable=True),
    sa.Column('qr_region', sa.JSON(), nullable=True),
    sa.Column('answer_regions', sa.JSON(), nullable=True),
    sa.Column('background_reference_path', sa.String(length=512), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['form_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scan_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('expected_sheet_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['form_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_sessions_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_sessions_task_id'), ['task_id'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=96), nullable=False),
    sa.Column('last_name', sa.String(length=96), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id', name='uq_students_external_id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_external_id'), ['external_id'], unique=False)

    op.create_table('scanned_sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('sheet_uid', sa.String(length=160), nullable=True),
    sa.Column('source_frame_path', sa.String(length=512), nullable=True),
    sa.Column('normalized_image_path', sa.String(length=512), nullable=True),
    sa.Column('enhanced_image_path', sa.String(length=512), nullable=True),
    sa.Column('answer_crop_path', sa.String(length=512), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=512), nullable=True),
    sa.Column('qr_payload', sa.JSON(), nullable=True),
    sa.Column('qr_status', sa.String(length=24), nullable=False),
    sa.Column('scan_status', sa.String(length=24), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('sharpness_score', sa.Float(), nullable=False),
    sa.Column('glare_score', sa.Float(), nullable=False),
    sa.Column('occlusion_score', sa.Float(), nullable=False),
    sa.Column('perspective_score', sa.Float(), nullable=False),
    sa.Column('coverage_score', sa.Float(), nullable=False),
    sa.Column('motion_score', sa.Float(), nullable=False),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['scanned_sheets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['scan_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scanned_sheets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scanned_sheets_qr_status'), ['qr_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_scanned_sheets_scan_status'), ['scan_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_scanned_sheets_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scanned_sheets_sheet_uid'), ['sheet_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_scanned_sheets_student_id'), ['student_id'], unique=False)

    op.create_table('recognition_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scanned_sheet_id', sa.Integer(), nullable=False),
    sa.Column('recognized_text', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=False),
    sa.Column('line_results_json', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('analysis_json', sa.JSON(), nullable=True),
    sa.Column('preprocess_variant', sa.String(length=64), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scanned_sheet_id'], ['scanned_sheets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recognition_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recognition_results_scanned_sheet_id'), ['scanned_sheet_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_recognition_results_status'), ['status'], unique=False)

    op.create_table('review_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scanned_sheet_id', sa.Integer(), nullable=False),
    sa.Column('teacher_text', sa.Text(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scanned_sheet_id'], ['scanned_sheets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_decisions_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_decisions_scanned_sheet_id'), ['scanned_sheet_id'], unique=True)

    op.create_table('scan_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('sheet_id', sa.Integer(), nullable=True),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.Column('corners', sa.JSON(), nullable=True),
    sa.Column('candidate_scores', sa.JSON(), nullable=True),
    sa.Column('selected_frame_index', sa.Integer(), nullable=False),
    sa.Column('qr_result', sa.String(length=255), nullable=True),
    sa.Column('processing_duration_ms', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['scan_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sheet_id'], ['scanned_sheets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_logs_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_logs_sheet_id'), ['sheet_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_logs_sheet_id'))
        batch_op.drop_index(batch_op.f('ix_scan_logs_session_id'))

    op.drop_table('scan_logs')
    with op.batch_alter_table('review_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_decisions_scanned_sheet_id'))
        batch_op.drop_index(batch_op.f('ix_review_decisions_decision'))

    op.drop_table('review_decisions')
    with op.batch_alter_table('recognition_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recognition_results_status'))
        batch_op.drop_index(batch_op.f('ix_recognition_results_scanned_sheet_id'))

    op.drop_table('recognition_results')
    with op.batch_alter_table('scanned_sheets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scanned_sheets_student_id'))
        batch_op.drop_index(batch_op.f('ix_scanned_sheets_sheet_uid'))
        batch_op.drop_index(batch_op.f('ix_scanned_sheets_session_id'))
        batch_op.drop_index(batch_op.f('ix_scanned_sheets_scan_status'))
        batch_op.drop_index(batch_op.f('ix_scanned_sheets_qr_status'))

    op.drop_table('scanned_sheets')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_external_id'))
        batch_op.drop_index(batch_op.f('ix_students_class_id'))

    op.drop_table('students')
    with op.batch_alter_table('scan_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_sessions_task_id'))
        batch_op.drop_index(batch_op.f('ix_scan_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_scan_sessions_class_id'))

    op.drop_table('scan_sessions')
    op.drop_table('camera_profiles')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_external_id'))

    op.drop_table('tasks')
    op.drop_table('hardware_events')
    op.drop_table('form_templates')
    op.drop_table('class_groups')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
